/** All user-facing strings in one place (PRD NFR-7). English only in v1. */
export const strings = {
  appName: 'Figtations',
  /** Major.minor injected from package.json at build time — see vite.config.ts. */
  version: `Beta V${__APP_VERSION__.split('.').slice(0, 2).join('.')}`,
  close: 'Close plugin',
  theme: { label: 'Panel theme', dark: 'Dark', light: 'Light' },
  tabs: { annotate: 'Annotate', all: 'All' },

  devModeBanner: 'Read-only in Dev mode — switch to Design mode to edit',

  emptySelection: {
    title: 'Select a layer to annotate',
    body: 'Annotations stay in sync while this plugin is open. If you move layers with it closed, reopen it or hit Refresh to bring the lines back in line.',
  },

  editor: {
    category: 'Category',
    noCategory: 'No category',
    editCategories: 'Edit categories…',
    labelPlaceholder: 'Add an annotation',
    addProperty: '+ Property',
    propertySearch: 'Search properties',
    noProperties: 'No properties available on this layer',
    multiSelection: (count: number) => `${count} layers selected — annotate all`,
    createAnnotation: 'Create annotation',
    createMany: (count: number) => `Create ${count} annotations`,
    createHint: 'Nothing is placed on the canvas until you create it. ⌘↵',
    createDisabledHint: 'Add a label or a property first.',
    line: 'Line',
    editLine: 'Edit line',
    pathEditHint: 'Press Enter to edit the line. Drag the handles, then click Done.',
    done: 'Done',
    resetLine: 'Reset line',
    straight: 'Straight',
    elbow: 'Elbow',
    exitSide: 'Exit side',
    customWidth: 'Custom width',
    resetWidth: 'Reset',
    selectTarget: 'Select target',
    duplicate: 'Duplicate',
    delete: 'Delete',
    notAnnotatable: 'This layer cannot be annotated',
    goToMainComponent: 'Go to main component',
    closePicker: 'Close property list',
    linkLibrary:
      'Library component — its main component lives in another file, which no plugin can jump to. Use right-click → Go to main component.',
    linkUnresolved: 'The main component could not be resolved for this instance.',
  },

  list: {
    search: 'Search annotations',
    orphans: 'Orphans',
    sortCanvas: 'Canvas order',
    sortCategory: 'Category',
    empty: 'No annotations on this page yet',
    noMatches: 'No annotations match your filters',
    detached: 'Detached',
    offPage: 'Off-page',
    freeNote: 'Free note',
    props: (count: number) => `${count} ${count === 1 ? 'prop' : 'props'}`,
    reattach: 'Reattach',
    keepAsFreeNote: 'Keep as free note',
    setCategory: 'Set category',
    arrangeSelected: 'Arrange',
    deleteSelected: 'Delete',
  },

  footer: {
    refresh: 'Refresh',
    arrange: 'Arrange',
    settings: 'Settings',
    // The panel is page-scoped, so "on this page" only cost width in the footer.
    counter: (count: number) => `${count} annotation${count === 1 ? '' : 's'}`,
  },

  categories: {
    title: 'Annotation categories',
    add: 'Add category',
    cancel: 'Cancel',
    done: 'Done',
    similarName: 'Similar name exists',
    deleteInUse: (count: number) =>
      `${count} annotation${count === 1 ? '' : 's'} use this category`,
    removeFromThem: 'Remove category from them',
    moveTo: 'Move to…',
    labelPlaceholder: 'Category name',
  },

  settings: {
    title: 'Settings',
    cardWidth: 'Card width',
    theme: 'Theme',
    dark: 'Dark',
    light: 'Light',
    connectorStyle: 'Connector style',
    connectorDashed: 'Dashed connector',
    cornerRadius: 'Corner radius',
    showEndpointDot: 'Endpoint dot',
    snapWaypoints: 'Snap waypoints',
    showPropertyValues: 'Show property values',
    showCardLayerName: 'Show layer name above the card',
    autoRefreshOnOpen: 'Refresh when the plugin opens',
    arrangeGutter: 'Arrange gutter',
    arrangeSide: 'Arrange side',
    left: 'Left',
    right: 'Right',
    rerenderWarning: (count: number) => `This re-renders ${count} cards on this page. Continue?`,
    nativeBridge: 'Native annotations',
    importNative: 'Import from native',
    exportNative: 'Export to native',
    deleteSourceAfterImport: 'Delete native annotations after import',
    scopePage: 'This page',
    scopeFile: 'Whole file',
  },

  resizeHandle: 'Resize the plugin window',

  confirm: { cancel: 'Cancel', confirm: 'Continue' },
} as const
